// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCas48jU2N5HDbEAuET35z1FrWwC6IqoLE',
    appId: '1:387228420362:web:2cb107456ce63bad6a12f3',
    messagingSenderId: '387228420362',
    projectId: 'lista-de-tarefas-cec0c',
    authDomain: 'lista-de-tarefas-cec0c.firebaseapp.com',
    storageBucket: 'lista-de-tarefas-cec0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbkMBxYQ45iVdFhNJlEPbBv2PgDkUXr0c',
    appId: '1:387228420362:android:72d6a26d08e8b4356a12f3',
    messagingSenderId: '387228420362',
    projectId: 'lista-de-tarefas-cec0c',
    storageBucket: 'lista-de-tarefas-cec0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjb4bVk6VduTbnl8-HWbxjfgss4UCqTHU',
    appId: '1:387228420362:ios:c96e3939e3d526ec6a12f3',
    messagingSenderId: '387228420362',
    projectId: 'lista-de-tarefas-cec0c',
    storageBucket: 'lista-de-tarefas-cec0c.appspot.com',
    iosClientId: '387228420362-b365iv845h5t89s7n0lre423cv53r30r.apps.googleusercontent.com',
    iosBundleId: 'com.example.listaDeTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjb4bVk6VduTbnl8-HWbxjfgss4UCqTHU',
    appId: '1:387228420362:ios:c96e3939e3d526ec6a12f3',
    messagingSenderId: '387228420362',
    projectId: 'lista-de-tarefas-cec0c',
    storageBucket: 'lista-de-tarefas-cec0c.appspot.com',
    iosClientId: '387228420362-b365iv845h5t89s7n0lre423cv53r30r.apps.googleusercontent.com',
    iosBundleId: 'com.example.listaDeTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCas48jU2N5HDbEAuET35z1FrWwC6IqoLE',
    appId: '1:387228420362:web:e30f115ce69bb0a66a12f3',
    messagingSenderId: '387228420362',
    projectId: 'lista-de-tarefas-cec0c',
    authDomain: 'lista-de-tarefas-cec0c.firebaseapp.com',
    storageBucket: 'lista-de-tarefas-cec0c.appspot.com',
  );
}
